#  * Copyright or © or Copr. Lucielle <pro@lucielle.ch> (2024 - 3024)
#  *
#  * This yaml file is all the settings to setup my NginX-proxy-manager
#  *
#  * This software is governed by the CeCILL license under French law and
#  * abiding by the rules of distribution of free software.  You can  use,
#  * modify and/ or redistribute the software under the terms of the CeCILL
#  * license as circulated by CEA, CNRS and INRIA at the following URL
#  * "http://www.cecill.info".
#  *
#  * As a counterpart to the access to the source code and  rights to copy,
#  * modify and redistribute granted by the license, users are provided only
#  * with a limited warranty  and the software's author,  the holder of the
#  * economic rights,  and the successive licensors  have only  limited
#  * liability.
#  *
#  * In this respect, the user's attention is drawn to the risks associated
#  * with loading,  using,  modifying and/or developing or reproducing the
#  * software by the user in light of its specific status of free software,
#  * that may mean  that it is complicated to manipulate,  and  that  also
#  * therefore means  that it is reserved for developers  and  experienced
#  * professionals having in-depth computer knowledge. Users are therefore
#  * encouraged to load and test the software's suitability as regards their
#  * requirements in conditions enabling the security of their systems and/or
#  * data to be ensured and,  more generally, to use and operate it in the
#  * same conditions as regards security.
#  *
#  * The fact that you are presently reading this means that you have had
#  * knowledge of the CeCILL license and that you accept its terms.

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: '10.0.0.20'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'nginxManager'
      DB_POSTGRES_PASSWORD: '' # TODO
      DB_POSTGRES_NAME: 'nginxManager'
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      server:
        ipv4_address: 10.0.0.2

networks:
  default:
    external: true
    name: server